image: archlinux
sources:
  - https://git.sr.ht/~xaffe/card-librarian
secrets:
  - 5a47b616-c112-4670-b09d-edf81df628a0
  - 22c56a11-980b-401d-9522-b07d4e3e4f3d
  - c4af631b-92bd-4d2b-862c-b1f6ebad7e3d
  - 43cd4dd3-cfc2-4e49-b623-92779fde694e
packages:
  - nvm
  - docker
  - rsync
  - postgresql-libs
tasks:
  - setup: |
      . ~/card-librarian/scripts/setup-docker.sh
      . ~/card-librarian/scripts/setup-ci.sh

  - checking-backend-sources: |
      . ~/card-librarian/scripts/setup-ci.sh
      cd ~/card-librarian
      npm run lint
      npm run build
      docker build .
      # if not on develop branch the next stages
      if [ "$(git rev-parse origin/develop)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi

  - deploy-backend: |
      curl -X POST $(< ~/slack-webhook-url) -d '{ "text": "Starting deployment of https://mtg.tim.schumacher.im", "format": "plain", "displayName": "Card Librarian CI", "avatarUrl": "https://mtg.tim.schumacher.im/assets/apple-touch-icon.png" }' -H 'Content-Type: application/json'
      . ~/card-librarian/scripts/setup-ci.sh
      cd ~/card-librarian
      export VERSION=$(node -e 'console.log(require("./package.json").version)')
      docker build -t cardlibrarian/backend:$VERSION.$JOB_ID .
      docker login -u cardlibrarian -p $(< ~/.docker-secret)
      docker push cardlibrarian/backend:$VERSION.$JOB_ID
      curl -X POST $(< ~/slack-webhook-url) -d '{ "text": "Successfully deployed app to https://mtg.tim.schumacher.im", "format": "plain", "displayName": "Card Librarian CI", "avatarUrl": "https://mtg.tim.schumacher.im/assets/apple-touch-icon.png" }' -H 'Content-Type: application/json'
