version: '3'
services:
    api:
        image: cardlibrarian/backend:0.1.0.23
        command: start:prod
        depends_on:
            - db
        environment:
            - NODE_ENV=development
            - NODE_CONFIG_ENV=production
        volumes:
            - /srv/services/mtg.tim.schumacher.im/files:/srv/backend/files/media
            - /srv/services/mtg.tim.schumacher.im/production.json:/opt/card-librarian/config/production.json
        ports:
            - 127.0.0.1:8014:3001
    db:
        image: postgres:12
        volumes:
            - /srv/services/mtg.tim.schumacher.im/database:/usr/local/var/lib/postgresql
        environment:
            - "PGDATA=/usr/local/var/lib/postgresql"
